travis: Enable travis to check odp-dpdk CI
Signed-off-by: Balakrishna Garapati <balakrishna.garapati@linaro.org>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@
 language: c
 sudo: required
 dist: trusty
+group: deprecated-2017Q2
 env:
   global:
     # COVERITY_SCAN_TOKEN
@@ -19,7 +20,7 @@ env:
     # The secure key to be filled below is the 685 character long encrypted
     # token you can find as follow from your coverity dashboard
     # (at https://scan.coverity.com/dashboard):
-    # Click on the github project (<you>/odp)
+    # Click on the github project (<you>/odp-dpdk)
     # Click on "submit build"
     # Click on "Configure Travis CI"
     # Look at the COVERITY_SCAN_TOKEN in the env: global: section
@@ -37,11 +38,11 @@ addons:
         apt:
                 sources:
                         - ubuntu-toolchain-r-test
-                        - llvm-toolchain-precise-3.8
                 packages:
                         - gcc
                         - clang-3.8
-                        - automake autoconf autoconf-archive libtool libssl-dev graphviz mscgen doxygen
+                        - automake autoconf libtool libssl-dev graphviz mscgen doxygen
+                        - autoconf-archive libconfig-dev
                         - libpcap-dev
 #        coverity_scan:
 #                project:
@@ -53,7 +54,6 @@ addons:
 
 compiler:
         - gcc
-        - clang-3.8
 
 env:
         - CONF=""
@@ -61,31 +61,49 @@ env:
         - CONF="--enable-schedule-sp"
         - CONF="--enable-schedule-iquery"
 
-install:
-        - echo 1000 | sudo tee /proc/sys/vm/nr_hugepages
-        - sudo mkdir -p /mnt/huge
-        - sudo mount -t hugetlbfs nodev /mnt/huge
+before_install:
 
+        # Install cross toolchains, etc
+        # apt-get update may fail thanks to Ubuntu removing Packages/indices while not removing relevant parts of Release file
+        - if [ -n "$CROSS_ARCH" ] ;
+          then
+                  BUILD_GNU_TYPE=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_BUILD_GNU_TYPE` ;
+                  CROSS_GNU_TYPE=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_HOST_GNU_TYPE` ;
+                  CROSS_MULTIARCH=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_HOST_MULTIARCH` ;
+                  CROSS="--host="$CROSS_GNU_TYPE" --build="$BUILD_GNU_TYPE" --prefix=/usr --includedir=/usr/include/"$CROSS_MULTIARCH" --libdir=/usr/lib/"$CROSS_MULTIARCH" --libexecdir=/usr/lib/"$CROSS_MULTIARCH"" ;
+                  sudo dpkg --add-architecture "$CROSS_ARCH" ;
+                  sudo -E apt-add-repository -y "deb http://ports.ubuntu.com trusty main" ;
+                  sudo -E apt-add-repository -y "deb http://ports.ubuntu.com trusty-updates main" ;
+                  sudo -E apt-get -y update || true ;
+                  sudo -E apt-get -y --no-install-suggests --no-install-recommends --force-yes install build-essential gcc-"$CROSS_GNU_TYPE" pkg-config-"$CROSS_GNU_TYPE" ;
+                  sudo -E apt-get -y --no-install-suggests --no-install-recommends --force-yes install libc6-dev:"$CROSS_ARCH" libssl-dev:"$CROSS_ARCH" zlib1g-dev:"$CROSS_ARCH" libconfig-dev:"$CROSS_ARCH" ;
+          fi
+
+        # Install cunit for the validation tests because distro version is too old and fails C99 compile
+        - sudo apt-get remove libcunit1-dev libcunit1
+        - export CUNIT_VERSION=2.1-3
+        - curl -sSOL https://github.com/Linaro/libcunit/releases/download/${CUNIT_VERSION}/CUnit-${CUNIT_VERSION}.tar.bz2
+        - tar -jxf *.bz2
+        - pushd CUnit*
+        - libtoolize --force --copy
+        - aclocal
+        - autoheader
+        - automake --add-missing --include-deps --copy
+        - autoconf
+        - ./configure --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test $CROSS || cat config.log
+        - make
+        - sudo make install
+        - popd
+        - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
+
+install:
         - sudo apt-get -qq update
         - sudo apt-get install linux-headers-`uname -r`
         - sudo pip install coverage
         - gem install asciidoctor
         - PATH=${PATH//:\.\/node_modules\/\.bin/}
 
-#       Install cunit for the validation tests because distro version is too old and fails C99 compile
-        - sudo apt-get remove libcunit1-dev libcunit1
-        - export CUNIT_VERSION=2.1-3
-        - curl -sSOL https://github.com/Linaro/libcunit/releases/download/${CUNIT_VERSION}/CUnit-${CUNIT_VERSION}.tar.bz2
-        - tar -jxf *.bz2
-        - pushd CUnit*
-        - ./bootstrap
-        - ./configure --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test
-        - make
-        - sudo make install
-        - popd
-        - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
-
-#	DPDK pktio
+#	DPDK
         - TARGET=${TARGET:-"x86_64-native-linuxapp-gcc"}
         - git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v17.02 http://dpdk.org/git/dpdk dpdk
         - pushd dpdk
@@ -93,33 +111,26 @@ install:
         - make config T=${TARGET} O=${TARGET}
         - pushd ${TARGET}
         - sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_PCAP=).*,\1y,' .config
+        - sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_OPENSSL=).*,\1y,' .config
         - popd
-        - make install T=${TARGET} EXTRA_CFLAGS="-fPIC"
-        - popd
-
-#	Netmap pktio
-        - git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v11.2 https://github.com/luigirizzo/netmap.git
-        - pushd netmap/LINUX
-        - ./configure
-        - make
-        - sudo insmod ./netmap.ko
+        - make -j install T=${TARGET} EXTRA_CFLAGS="-fPIC"
         - popd
 
 script:
         - ./bootstrap
-        - ./configure --prefix=$HOME/odp-install  --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-dpdk-path=`pwd`/dpdk/${TARGET} --with-netmap-path=`pwd`/netmap $CONF
-        - make -j $(nproc)
+        - ./configure --prefix=$HOME/odp-dpdk-install  --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET} $CONF
+        - make -j
         - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" make check
         - make install
 
-        - echo "Checking linking and run from install..."
-        - pushd $HOME
-        - echo "Dynamic link.."
-        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst -I${HOME}/odp-install/include -L${HOME}/odp-install/lib -lodp-linux -L${OLDPWD}/dpdk/x86_64-native-linuxapp-gcc/lib -lrt -ldpdk -lpthread -lcrypto -lpcap -ldl
-        - LD_LIBRARY_PATH="${HOME}/odp-install/lib:$LD_LIBRARY_PATH" ./odp_hello_inst
-        - echo "Static link.."
-        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst -I${HOME}/odp-install/include -L${HOME}/odp-install/lib -lodp-linux -L${OLDPWD}/dpdk/x86_64-native-linuxapp-gcc/lib -lrt -ldpdk -lpthread -lcrypto -lpcap -ldl -static
-        - ./odp_hello_inst
+#        - echo "Checking linking and run from install..."
+#        - pushd $HOME
+#        - echo "Dynamic link.."
+#        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-dpdk-install/lib/pkgconfig pkg-config --cflags --libs libodp-dpdk`
+#        - LD_LIBRARY_PATH="${HOME}/odp-dpdk-install/lib:$LD_LIBRARY_PATH" ./odp_hello_inst
+#        - echo "Static link.."
+#        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-dpdk-install/lib/pkgconfig pkg-config --cflags --libs libodp-dpdk --static` -static
+#        - ./odp_hello_inst
 
 jobs:
         include:
@@ -128,23 +139,23 @@ jobs:
                   compiler: gcc
                   script:
                           - ./bootstrap
-                          - ./configure --prefix=$HOME/odp-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-dpdk-path=`pwd`/dpdk/${TARGET} --with-netmap-path=`pwd`/netmap CFLAGS="-O0 -coverage" CXXFLAGS="-O0 -coverage" LDFLAGS="--coverage"
+                          - ./configure --prefix=$HOME/odp-dpdk-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET} CFLAGS="-O0 -coverage" CXXFLAGS="-O0 -coverage" LDFLAGS="--coverage"
                           - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" PATH=${PATH//:\.\/node_modules\/\.bin/} make check
                           - find . -type f -iname '*.[ch]' -not -path ".git/*" -execdir gcov {} \; ; bash <(curl -s https://codecov.io/bash) -X coveragepy
-                - stage: test
-                  env: TEST=distcheck
-                  compiler: gcc
-                  script:
-                          - ./bootstrap
-                          - ./configure
-                          - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" make distcheck
+#                - stage: test
+#                  env: TEST=distcheck
+#                  compiler: gcc
+#                  script:
+#                          - ./bootstrap
+#                          - ./configure --prefix=$HOME/odp-dpdk-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET}
+#                          - sudo PATH="$PATH" LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" make distcheck
                 - stage: test
                   env: TEST=doxygen
                   compiler: gcc
                   script:
                           # doxygen does not trap on warnings, check for them here.
                           - ./bootstrap
-                          - ./configure
+                          - ./configure --with-sdk-install-path=`pwd`/dpdk/${TARGET}
                           - make doxygen-doc |tee doxygen.log
                           - fgrep -rvq warning ./doxygen.log
                 - stage: test
@@ -152,9 +163,10 @@ jobs:
                   compiler: gcc
                   script:
                           - echo ${TRAVIS_COMMIT_RANGE};
-                          - ODP_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
-                          - if [ -z "${ODP_PATCHES}" ]; then env; exit 1; fi;
-                          - ./scripts/ci-checkpatches.sh ${ODP_PATCHES};
+                          - ODP_DPDK_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
+                          - if [ -z "${ODP_DPDK_PATCHES}" ]; then env; exit 1; fi;
+                          - ./scripts/ci-checkpatches.sh ${ODP_DPDK_PATCHES};
 
 after_failure:
+  - cat config.log
   - find . -name 'test-suite.log' -execdir grep -il "FAILED" {} \; -exec echo {} \; -exec cat {} \;
